### ISSUE TITLE
couldn't download brackets from brackets.io

### ISSUE THREAD

**Issue by chitanyachitturi** [brackets-cont/brackets#17] opened 2021-09-09 15:07 UTC
MacOS BigSur Version 11.5.2

**Comment by N-yaya** [comment] 2021-09-09 18:47
the doawload button for brackets not reacting

**Comment by ScanuNicco** [comment] 2021-09-09 23:22
This is caused by a cert error on the new S3 bucket that the website is using. For now, you can download Brackets from the old Adobe repo: https://github.com/adobe/brackets/releases

**Comment by King-of-the-Bill** [comment] 2021-09-20 01:39
Why does this main fork not have .msi or .dmg installers in the releases? This would be the best fix while the site gets its act together.

**Comment by abose** [comment] 2021-10-05 08:26
Duplicate of https://github.com/brackets-cont/brackets/issues/19
Closing.

**Closed by abose** 2021-10-05 08:26 UTC
