### ISSUE TITLE
Can't install extensions (registry link is down)

### ISSUE THREAD

**Issue by anghelos** [brackets-cont/brackets#15] opened 2021-09-03 01:27 UTC
I imagine that the move is pretty fresh, and it's expected to have issues like this one, but it would really be appreciated if we could get registry.brackets.io up and running again!

I just started teaching a web design class with only brackets installed as a code editor on the class computers and no admin access, so it's impossible to install extensions like Emmet, which have other dependencies (without being able to run npm).

Cheers !

**Comment by ScanuNicco** [comment] 2021-09-03 02:19
https://registry.brackets.io/ has actually been up for a few hours. The problem is that https isn't working yet so brackets won't connect.

**Comment by dym-sh** [comment] 2021-09-07 11:33
github-signin relocates to `https://localhost:3000/auth/github/callback?code=f6fa57e8968d2c2af9a7` after auth

**Comment by kanta-mir** [comment] 2021-09-12 20:50
use this link . copy the link and past in the url box of the themes and plugins
https://cdn.amuslim.org/brackets/

**Comment by Huygenz** [comment] 2021-09-13 11:21
ScanuNicco already posted the correct link to the working registry. I hope we'll get that cert working soon to avoid splits like this.

**Comment by rileyhawk1417** [comment] 2021-09-15 14:52
@Huygenz has there been any luck in trying to rebuild brackets with the updated dependancies? Was thinking of going in the config files and updating links such as the "extensions registry". Cant say I know how to build programs from scratch but I can try tweak where I can.

**Comment by ScanuNicco** [comment] 2021-09-19 20:35
I think the first step for now is for someone with write access to make a `release-1.14.3` branch based off of the existing `release-1.14.2` branch so we can update the URL on a stable version of brackets (the `master` branch is an unfinished version of brackets 1.15). Then we can apply the link fixes from #11 as well as updating the registry link. Then I can take a shot at building it but I've never built brackets from source before so I might not be able to get it working.

**Comment by rileyhawk1417** [comment] 2021-09-19 21:13
That sounds good, cloned the repo locally but when installing npm packages it hits an error when dealing with grunt not sure why.

**Comment by ScanuNicco** [comment] 2021-09-19 21:40
I think most of the dependencies are pretty out of date. Maybe try the source from #2?

**Comment by rileyhawk1417** [comment] 2021-09-19 21:45
Seems like the PR is still waiting to be approved.

**Comment by rileyhawk1417** [comment] 2021-09-20 09:27
@ScanuNicco Used the one from #2 ran fine on linux. Am yet to test windows, want to try and add grunt-contrib-sass. Only saw grunt-contrib-less in the packages.

**Comment by ScanuNicco** [comment] 2021-09-20 18:38
You might want to leave a comment on #2 saying that you got it to run. I don't think anyone else has gotten it to run yet, so you could help get it merged.

**Comment by rileyhawk1417** [comment] 2021-09-20 21:06
@ScanuNicco I did leave a comment there not sure if the reviewers will notice it.

**Comment by willnode** [comment] 2021-09-23 23:49
I still watching that PR 👀 if anyone found there's something problem with it I can help.

**Comment by willnode** [comment] 2021-10-02 00:32
Btw, do we fully owns the registry? worried if https://registry.brackets.s3.amazonaws.com/ will go down in some later point in time.

**Comment by abose** [comment] 2021-12-07 16:02
Bracket 2.0.1 is out with extension registry owned by the community.
Closing as fixed.

**Closed by abose** 2021-12-07 16:02 UTC
