### ISSUE TITLE
Uninstall on macOS Monterey not functional?

### ISSUE THREAD

**Issue by e-williams** [brackets-cont/brackets#55] opened 2021-11-11 21:02 UTC
### Problem
Cannot uninstall (move to trash) Brackets application

### Troubleshoot
Have ensured application not running in listed processes

### Specs
Brackets version: 1.14.2
macOS Monterey 12.0.1

**Comment by charlypa** [comment] 2021-11-12 05:45
@e-williams   Apologies for the error. Could you share whats is the behaviour when you try to uninstall the application?

**Comment by e-williams** [comment] 2021-11-12 17:42
Sure. When I move the application icon to the trash, it moves back up to its original position. However, I just attempted uninstallation by selecting the application in Finder and then selecting trash and it worked. I'm not sure why there's a discrepancy in action in this case but it seems the problem has been resolved. Thanks for your interest.

**Comment by abose** [comment] 2021-11-12 17:46
Closing as the issue is resolved.

**Closed by abose** 2021-11-12 17:46 UTC
