### ISSUE TITLE
Is Linux no longer supported?

### ISSUE THREAD

**Issue by inf3rno** [brackets-cont/brackets#203] opened 2022-06-29 14:12 UTC
I go to the link you wrote in the readme.md and got only Windows and Mac installers. https://github.com/brackets-cont/brackets/releases
Nothing about the Linux install for example on Debian or Ubuntu. No recommended repository, etc. I managed to get it with snap on Debian + XFCE, but snap is not integrated with the desktop environment, so the icon did not show up on the desktop. Drag & drop did not work either, maybe because of this snap install. It would be nice to have some sort of support.

**Comment by zer0kool** [comment] 2022-07-07 02:44
Do we have any updates from devs that anyone could share?

**Comment by abose** [comment] 2022-07-07 05:39
Hello, an official Linux release is at-least a few months away as we try to stabilize phoenix [phcode.dev]( https://phcode.dev ).
Future builds of brackets will be based on Phoenix and we are trying to get it done in 2-3 months. 

In the mean time, please use phcode.dev in a chrome based browser in phoenix and provide feedback if any as it is mostly Linux/future brackets releases under development.

**Comment by Syndicoon** [comment] 2022-08-19 13:43
I have read this canned reply before.... always the same: "a few months away..." Then suddenly we find an online-only version posted. So this tells me that NO, Linux is no longer supported or even thought about. How long does it take to compile the source into a Linux package? It can't be longer than MAC since that is also Unix. The reasoning of needing to "stabilize phcode.dev" is very telling. Are you saying the Linux users have nothing to contribute to this cause? You also can't tell me that there isn't someone on the team that can do this. If that is the case, then this tells me all I need to know. Linux users will have the option of working online only. If you want to work off-line... tough luck. Not cool.

**Comment by abose** [comment] 2022-08-19 14:06
@Syndicoon  Native Linux builds are being worked on. Infact our primary dev environment right now we use to build Phoenix is Linux. The next release of phoenix/brackets will have native builds for all platforms ready and brackets 2.1(current) would most likely be the last legacy build of brackets to be based on adobe brackets-shell. 

The reason we are doing phcode.dev is to be able to port brackets to any platform- be it linux/unix/android/windows/mac/arm64/raspberry pi. That is a pretty huge platform list to support overnight and we are working on as fast as we can. 

To learn more of the complexities on why Linux builds are taking time, please read the following issues:
1. https://github.com/brackets-cont/brackets/issues/26
2. https://github.com/brackets-cont/brackets/issues/112

Closing this issue as duplicate of https://github.com/brackets-cont/brackets/issues/112 which is the master tracing ticket for Linux.

Please update your further comments and suggestions in the master ticket.

**Closed by abose** 2022-08-19 14:06 UTC

**Comment by inf3rno** [comment] 2022-08-19 14:15
@abose Thanks!
